---
- hosts: all
  sudo: yes
  accelerate: true
  vars_files:
    - vars.yml
  roles:
    - common
- hosts: all
  sudo: no
  accelerate: true
  vars_files:
    - vars.yml
  roles:
    - dbserver
    - appserver