---
- hosts: all
  sudo: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Bootstrap accelerated mode: Install keyczar
      action: apt pkg=python-keyczar state=installed update-cache=yes
- hosts: all
  sudo: yes
  accelerate: true
  vars_files:
    - vars.yml
  roles:
    - common
- hosts: all
  sudo: no
  accelerate: true
  vars_files:
    - vars.yml
  roles:
    - dbserver
    - appserver