- name: ensure postgres is installed
  action: apt pkg=${item} state=installed update-cache=yes
  sudo: yes
  with_items:
    - postgresql-9.1-postgis
    - postgresql-server-dev-9.1
    - libgeos-dev
    - python-psycopg2


- name: Create postgresql user
  action: postgresql_user user=${dbuser} password=${dbpassword} role_attr_flags=CREATEDB,NOSUPERUSER
  sudo_user: postgres
  sudo: yes

- name: ensure database is created
  action: postgresql_db db=$dbname owner=$dbuser encoding='UTF-8' lc_ctype='en_US.UTF-8' lc_collate='en_US.UTF-8'
  sudo_user: postgres
  sudo: yes
  register: db_created

- name: create postgis extension
  action: command psql -c "CREATE EXTENSION postgis;" --dbname=$dbname
  sudo: yes
  sudo_user: postgres
  when: db_created.changed

- name: create postgis_topology extension
  action: command psql -c "CREATE EXTENSION postgis_topology;" --dbname=$dbname
  sudo: yes
  sudo_user: postgres
  when: db_created.changed

- name: ensure user has access to database
  sudo: yes
  sudo_user: postgres
  action: postgresql_user db=$dbname user=$dbuser password=$dbpassword priv=ALL

- name: ensure user does not have unnecessary privilege
  sudo: yes
  sudo_user: postgres
  action: postgresql_user user=$dbuser role_attr_flags=NOSUPERUSER,NOCREATEDB
